plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = '2.2.15'
group = 'com.heroclock'
base { archivesName = 'HeroClock' }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
    gameTest {
        compileClasspath += sourceSets.main.output + configurations.testCompileClasspath
        runtimeClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
    }
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        gameTestServer {
            workingDirectory project.file('run-gametest')
            property 'forge.enabledGameTestNamespaces', 'heroclock'
            mods {
                heroclock {
                    source sourceSets.main
                    source sourceSets.gameTest
                }
            }
        }
        server {
            workingDirectory project.file('run')
            args '--nogui'
            mods { heroclock { source sourceSets.main } }
        }
        client {
            workingDirectory project.file('run')
            mods { heroclock { source sourceSets.main } }
        }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://api.modrinth.com/maven' }
    maven { url = 'https://maven.minecraftforge.net' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
    if (project.hasProperty('withPalladium')) {
        runtimeOnly fg.deobf('maven.modrinth:threetag-palladium:4.5.9+1.20.1-forge')
    }
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    testImplementation platform('org.junit:junit-bom:5.10.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

tasks.named('test', Test) { useJUnitPlatform() }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.named('processResources', ProcessResources) {
    exclude 'patches/**', 'HEROCLOCK_PATCH_NOTES.txt'
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand(version: project.version) }
}
tasks.named('jar', Jar) {
    manifest.attributes('Implementation-Version': project.version,
                        'Implementation-Vendor': 'PunctualBoat',
                        'MixinConfigs': 'heroclock.mixins.json')
    finalizedBy 'reobfJar'
}

mixin {
    add sourceSets.main, 'heroclock.refmap.json'
    config 'heroclock.mixins.json'
}
